### ISSUE TITLE
Make main branch as the default branch

### ISSUE THREAD

**Issue by chaokunyang** [quarkiverse/quarkus-fury#1]
Hi @zhfeng , do you knwn how to configure main branch as the default branch?

**Comment by zhfeng** [comment]
@chaokunyang I think it is driven by [terraform scripts](https://github.com/quarkiverse/quarkiverse-devops/blob/main/terraform-scripts/quarkus-fury.tf)

Maybe we can use [github_branch_default](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/branch_default) to set the default branch like

```
resource "github_branch_default" "default"{
  repository = "quarkus-fury"
  branch     = "main"
}
```

@gastaldi WDYT?

**Comment by gastaldi** [comment]
@zhfeng that works, but I have already changed in the repository settings ;)

**Comment by gastaldi** [comment]
@quarkiverse/quarkiverse-fury I have also pushed a skeleton sample in the main branch, as I noticed the `initial_fury_support` branch was using a wrong GroupID and missing the `.github` scripts

**Comment by zhfeng** [comment]
Thanks a lot @gastaldi !

@chaokunyang can you check your codes in `initial_fury_support` can work wit the main branch?

**Comment by chaokunyang** [comment]
@zhfeng I just opened a PR https://github.com/quarkiverse/quarkus-fury/pull/5. There are somethings about quarkus which I'm not so sure. Let's discuss in the PR.
