### ISSUE TITLE
Add a icon-url in quarkus-extension.yaml

### ISSUE THREAD

**Issue by zhfeng** [quarkiverse/quarkus-fury#11]
It could be usefurl to add a icon-url for `quarkus-fury` when display in https://quarkus.io/extensions/

**Comment by zhfeng** [comment]
@chaokunyang Do you know where is the icon for `Fury`?

I found this one ![Fury logo](https://fury.apache.org/zh-CN/img/navbar-logo.svg "Fury logo"), is it right?

**Comment by chaokunyang** [comment]
Yeah, we could use this one
