### ISSUE TITLE
How to configure Language.

### ISSUE THREAD

**Issue by JackyAnn** [quarkiverse/quarkus-fury#39]
The default language is Language.Java
How to set Language to Language.XLANG

I didn't find any configuration in [FuryBuildTimeConfig](https://github.com/quarkiverse/quarkus-fury/blob/main/runtime/src/main/java/io/quarkiverse/fury/FuryBuildTimeConfig.java) either!

**Comment by zhfeng** [comment]
No, there is no such configuration currently. Just curious, what are your requirement to use `XLANG`?

**Comment by JackyAnn** [comment]
> Fury designed and implemented multiple binary protocols for different scenarios:
> - **[xlang serialization format](docs/specification/xlang_serialization_spec.md)**:
>   - Cross-language serialize any object automatically, no need for IDL definition, schema compilation and object to/from
>     protocol conversion.
>   - Support optional shared reference and circular reference, no duplicate data or recursion error.
>   - Support object polymorphism.
> - **[Java serialization format](docs/specification/java_serialization_spec.md)**: Highly-optimized and drop-in replacement > for Java serialization.
> - **[Row format format](docs/specification/row_format_spec.md)**: A cache-friendly binary random access format, > supports skipping serialization and
>   partial serialization, and can convert to column-format automatically.


I'm going to use fury to replace json in our web project.
This will require support for serialization in at least two languages, java and javascript.
Also go, python is becoming more and more popular in the backend and it's becoming more and more common to have a mixed language stack in microservices.

If I understand correctly, according to the documentation, the cross-language should use the xlang serialization format

**Comment by zhfeng** [comment]
@chaokunyang can you check it? I think we can add such Language Configuration but you maybe know more details.

**Comment by chaokunyang** [comment]
The xlang serialization in Fury Java doesn't support graalvm yet. Currently only Fury Java serialization protocol support graalvm. We are working on xlang format for graalvm, But it may still needs several weeks

**Comment by chaokunyang** [comment]
Yeah, We should introduce this configuration option
