### ISSUE TITLE
Rest client support

### ISSUE THREAD

**Issue by JackyAnn** [quarkiverse/quarkus-fury#40]
Are there any plans to add rest client support？

Quarkus provides two types of rest services [RESTEasy Classic](https://quarkus.io/guides/resteasy) and [REST](https://quarkus.io/guides/rest) which are implemented differently and have different dependencies.

And quarkus provide the differently rest client  implementation [resteasy-client](https://quarkus.io/guides/resteasy-client) and [rest-client](https://quarkus.io/guides/rest-client)

**Implementations and dependencies are also different  for different serializations**
[rest core](https://github.com/quarkusio/quarkus/tree/main/extensions/resteasy-reactive)
[resteasy classic core](https://github.com/quarkusio/quarkus/tree/main/extensions/resteasy-classic)
**For example**
_the jsonb serialization implementation for [REST](https://quarkus.io/guides/rest) and [rest-client](https://quarkus.io/guides/rest-client):_
```
implementation 'io.quarkus:quarkus-rest'
implementation 'io.quarkus:quarkus-rest-jsonb'
implementation 'io.quarkus:quarkus-rest-client-jsonb'
```

_the jsonb serialization implementation for [RESTEasy Classic](https://quarkus.io/guides/resteasy)  and [resteasy-client](https://quarkus.io/guides/resteasy-client):_
```
implementation 'io.quarkus:quarkus-resteasy'
implementation 'io.quarkus:quarkus-resteasy-jsonb'
implementation 'io.quarkus:quarkus-resteasy-client-jsonb'
```

**Comment by zhfeng** [comment]
Yeah, it should be easy to support `rest-client`. I'm working on it.
