### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by zhfeng** [quarkiverse/quarkus-fury#8]
- Init https://docs.quarkiverse.io/quarkus-fury/dev
- Add some examples for seriliazation.

**Comment by zhfeng** [comment]
- https://github.com/quarkiverse/quarkiverse-docs/pull/199

**Comment by zhfeng** [comment]
Hi @chaokunyang ,

Do you mind to update the `docs/modules/ROOT/pages/index.adoc` to add more detail about Apache Fury and maybe with some examples by using `@FurySerializaion` since you are the expert of `Fury` ?

All of the changes which are merged in the `main` branch will be published to https://docs.quarkiverse.io/quarkus-fury/dev/index.html automatically every 4 hours each day.

**Comment by chaokunyang** [comment]
I will do it tomorrow
